In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame({'col1' :[1,3,4,2,1],
             'co2':[35,45,56,53,67],
             'col3':"an kita ye ta le".split()
             })#convert list into dictionery 

In [10]:
"ankita rajendra yetale".split()
       

['ankita', 'rajendra', 'yetale']

In [11]:
df

col1  co2  col3
0     1   35    an
1     3   45  kita
2     4   56    ye
3     2   53    ta
4     1   67    le

In [15]:
df['col4'] = df['col3'].str[0]

In [16]:
df

col1  co2  col3 col5 col4
0     1   35    an    a    a
1     3   45  kita    k    k
2     4   56    ye    y    y
3     2   53    ta    t    t
4     1   67    le    l    l

In [19]:
def test(a):
    return a**2

In [20]:
df['col4_4'] = df['col1'].apply(test)

In [21]:
df

col1  co2  col3 col5 col4  col4_4
0     1   35    an    a    a       1
1     3   45  kita    k    k       9
2     4   56    ye    y    y      16
3     2   53    ta    t    t       4
4     1   67    le    l    l       1

In [22]:
#deriverd column for calculation

In [23]:
def test1(a):
    if a =='s':
        return 's'
    else:
        return 'z'

In [25]:
df['col6'] =df['col5'].apply(test1)

In [26]:
df

col1  co2  col3 col5 col4  col4_4 col6
0     1   35    an    a    a       1    z
1     3   45  kita    k    k       9    z
2     4   56    ye    y    y      16    z
3     2   53    ta    t    t       4    z
4     1   67    le    l    l       1    z

In [27]:
df['col6_6'] =df['col5'].apply(lambda a :'s' if a == 's' else 'z')

In [28]:
df

col1  co2  col3 col5 col4  col4_4 col6 col6_6
0     1   35    an    a    a       1    z      z
1     3   45  kita    k    k       9    z      z
2     4   56    ye    y    y      16    z      z
3     2   53    ta    t    t       4    z      z
4     1   67    le    l    l       1    z      z

In [29]:
df['col7'] = df['col3'].apply(len)

In [30]:
df

col1  co2  col3 col5 col4  col4_4 col6 col6_6  col7
0     1   35    an    a    a       1    z      z     2
1     3   45  kita    k    k       9    z      z     4
2     4   56    ye    y    y      16    z      z     2
3     2   53    ta    t    t       4    z      z     2
4     1   67    le    l    l       1    z      z     2

In [31]:
import math

In [33]:
df['col8'] = df['co2'].apply(math.log)

In [34]:
df

col1  co2  col3 col5 col4  col4_4 col6 col6_6  col7      col8
0     1   35    an    a    a       1    z      z     2  3.555348
1     3   45  kita    k    k       9    z      z     4  3.806662
2     4   56    ye    y    y      16    z      z     2  4.025352
3     2   53    ta    t    t       4    z      z     2  3.970292
4     1   67    le    l    l       1    z      z     2  4.204693

In [35]:
#numpy = numerical python
import numpy as np

In [36]:
l = ['ank',2,3,45,6]

In [38]:
type(l)

list

In [39]:
np.array(l)

array(['ank', '2', '3', '45', '6'], dtype='<U11')

In [40]:
np.array([4,5,6,7,2,2])

array([4, 5, 6, 7, 2, 2])

In [41]:
np.array([[23,45] , [20,95]])

array([[23, 45],
       [20, 95]])

In [49]:
a2 = np.array([1,2,3,4],ndmin = 4)

In [50]:
a2[0]

array([[[1, 2, 3, 4]]])

In [51]:
a2[0][0][0][0]

1

In [54]:
a = [2,3,4,2]
np.asarray(a)

array([2, 3, 4, 2])

In [55]:
np.asarray(np.mat(a))

array([[2, 3, 4, 2]])

In [56]:
np.mat(a)#matrix is subclass/part of array

matrix([[2, 3, 4, 2]])

In [57]:
#matrix has 2 two dimensional

In [59]:
np.fromfunction(lambda i , j: i==j, (3,2))

array([[ True, False],
       [False,  True],
       [False, False]])

In [96]:
a = np.fromfunction(lambda i , j ,z :i*j*z , (4,3,2))

In [101]:
a.reshape(4,2,1,3,1,1)

array([[[[[[0.]],

          [[0.]],

          [[0.]]]],



        [[[[0.]],

          [[0.]],

          [[0.]]]]],




       [[[[[0.]],

          [[0.]],

          [[0.]]]],



        [[[[1.]],

          [[0.]],

          [[2.]]]]],




       [[[[[0.]],

          [[0.]],

          [[0.]]]],



        [[[[2.]],

          [[0.]],

          [[4.]]]]],




       [[[[[0.]],

          [[0.]],

          [[0.]]]],



        [[[[3.]],

          [[0.]],

          [[6.]]]]]])

In [98]:
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 1.],
        [0., 2.]],

       [[0., 0.],
        [0., 2.],
        [0., 4.]],

       [[0., 0.],
        [0., 3.],
        [0., 6.]]])

In [74]:
a.size

27

In [77]:
a.ndim

3

In [78]:
a.shape#dimension

(3, 3, 3)

In [79]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 1., 2.],
        [0., 2., 4.]],

       [[0., 0., 0.],
        [0., 2., 4.],
        [0., 4., 8.]]])

In [82]:
#dataframe is 2D array

In [83]:
a = np.fromfunction(lambda i , j  :i*j , (3,3))

In [84]:
a

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [85]:
pd.DataFrame(a)#conversion of array to dataframe

0    1    2
0  0.0  0.0  0.0
1  0.0  1.0  2.0
2  0.0  2.0  4.0

In [86]:
np.random.rand(100,4)#generate values

array([[2.49895268e-01, 9.14098584e-02, 6.97655809e-01, 6.68084943e-01],
       [6.60606175e-01, 9.65841475e-03, 8.89095828e-01, 1.59259152e-01],
       [4.80121406e-01, 5.07096813e-01, 8.73524137e-01, 9.54048265e-01],
       [5.01123493e-01, 4.86415492e-01, 9.47237348e-02, 4.41970564e-01],
       [8.46140030e-01, 5.49606524e-01, 6.49777473e-01, 1.67133750e-01],
       [4.07588202e-01, 1.79280951e-01, 1.64723555e-01, 8.11615974e-01],
       [2.19901211e-01, 3.58245695e-01, 1.26292255e-01, 6.51966503e-01],
       [9.19019096e-01, 2.25082870e-01, 1.76893864e-01, 4.17232282e-01],
       [6.87923838e-01, 9.79624940e-01, 3.30995358e-01, 5.26114338e-01],
       [6.92923242e-01, 1.62661667e-01, 7.47975849e-01, 5.17875571e-01],
       [9.32724425e-01, 3.67477544e-01, 8.74388976e-01, 4.93421847e-01],
       [2.31955570e-01, 9.66275273e-02, 4.75779561e-01, 3.31582477e-01],
       [4.33984937e-01, 6.70726575e-01, 2.38606780e-02, 4.27733616e-01],
       [1.39347561e-02, 5.59548905e-01, 7.37143373e

In [87]:
np.random.randint(4,50)#generate random integer

24

In [89]:
np.random.randn(4,5)#generate normally distrubuted no

array([[ 0.47121529, -0.78033161, -1.25525642, -0.82620756, -0.00622823],
       [-0.21369689, -2.09915057, -0.55809141,  1.74863175,  0.46389545],
       [-1.08067166, -0.06075127, -0.58661147,  0.8195441 ,  0.06787968],
       [ 0.57721167, -0.0216094 , -0.42009396, -0.02980717,  0.31384526]])

In [90]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -1.267641  0.136102 -0.781376  0.510202 -0.384349
1 -0.238171 -0.149251  2.267314  0.808744  1.646431
2  1.464876 -0.285174 -0.325374 -1.161804  0.514639
3 -0.386697  0.039259 -0.368903  1.275318 -1.112397

In [104]:
list(range(3,9,2))#jump of two

[3, 5, 7]

In [108]:
np.arange(4,10,.2)#floating step size

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [109]:
a1=np.arange(4,10,.2)

In [110]:
a1

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [111]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [112]:
arr = np.random.rand(4,5)

In [113]:
arr

array([[0.99229034, 0.99314422, 0.01615252, 0.53067454, 0.25756292],
       [0.14356779, 0.02306573, 0.15448119, 0.68484343, 0.81745132],
       [0.88876103, 0.44841474, 0.40646649, 0.87456465, 0.86759028],
       [0.18988509, 0.66782184, 0.30321769, 0.64850889, 0.89819805]])

In [114]:
arr[arr > .5]

array([0.99229034, 0.99314422, 0.53067454, 0.68484343, 0.81745132,
       0.88876103, 0.87456465, 0.86759028, 0.66782184, 0.64850889,
       0.89819805])

In [115]:
arr

array([[0.99229034, 0.99314422, 0.01615252, 0.53067454, 0.25756292],
       [0.14356779, 0.02306573, 0.15448119, 0.68484343, 0.81745132],
       [0.88876103, 0.44841474, 0.40646649, 0.87456465, 0.86759028],
       [0.18988509, 0.66782184, 0.30321769, 0.64850889, 0.89819805]])

In [116]:
arr[1:8 , 0:3]

array([[0.14356779, 0.02306573, 0.15448119],
       [0.88876103, 0.44841474, 0.40646649],
       [0.18988509, 0.66782184, 0.30321769]])